Mangata dev v0.9.29
mangata-finance/open-runtime-module-library pull request #24
Opened 2022-10-21 14:32 UTC by devdanco

2022-10-26 17:42 UTC, iStrike7 requested changes

2022-10-26 17:42 UTC, iStrike7 commented on asset-registry/src/lib.rs
> +			// LastAssetId::<T>::set(self.last_asset_id.clone());
Please remove all comment references to LastAssetId, including the storage item definition on line 103

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer(currency_id.clone(), *amount, dest))]
Please revert this change! This was the reason xcm transfers was crashing the whole network!

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> -		#[transactional]
Why is this extrinsic no longer transactional?

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer(currency_id.clone(), *amount, dest))]
Please revert this change! This was the reason xcm transfers was crashing the whole network!

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer_multicurrencies(currencies, fee_item, dest))]
Please revert this change! This was the reason xcm transfers was crashing the whole network!

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> -		#[transactional]
Why is this extrinsic no longer transactional?

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> -		#[transactional]
Why is this extrinsic no longer transactional?

2022-10-26 17:42 UTC, iStrike7 commented on xtokens/src/lib.rs
> -
Please revert this change! This was the reason xcm transfers was crashing the whole network!

2022-10-26 18:49 UTC, devdanco commented on asset-registry/src/lib.rs
> +			// LastAssetId::<T>::set(self.last_asset_id.clone());
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer(currency_id.clone(), *amount, dest))]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> -		#[transactional]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer(currency_id.clone(), *amount, dest))]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> +		#[pallet::weight(Pallet::<T>::weight_of_transfer_multicurrencies(currencies, fee_item, dest))]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> -		#[transactional]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> -		#[transactional]
done

2022-10-26 18:50 UTC, devdanco commented on xtokens/src/lib.rs
> -
done

2022-10-28 07:52 UTC, mateuszaaa approved these changes
lgtm, just make sure that try-runtime works

2022-10-28 19:36 UTC, devdanco commented
@mateuszaaa try-runtime works :)

2022-10-31 16:15 UTC, iStrike7 approved these changes

2022-11-01 08:26 UTC, merged